# Generated by Django 5.2.14 on 2026-06-01 15:29

import django.contrib.postgres.fields
import scheduling.workflows.parsing.liturgical
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0038_alter_historicalschedulingmoderation_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexevent',
            name='periods',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=scheduling.workflows.parsing.liturgical.PeriodEnum.choices, max_length=16), default=list, size=None),
        ),
    ]
