# Generated by Django 5.2.14 on 2026-06-25 16:05

import django.db.models.deletion
import pgvector.django.vector
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0039_indexevent_periods'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Encoder',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('prod', 'Prod')], max_length=5)),
                ('base_model', models.CharField(max_length=100)),
                ('hf_repo_id', models.CharField(max_length=200)),
                ('hf_revision', models.CharField(max_length=100, null=True)),
                ('dimensions', models.PositiveSmallIntegerField()),
                ('accuracy_temporal', models.FloatField(null=True)),
                ('accuracy_confession', models.FloatField(null=True)),
                ('test_size', models.PositiveSmallIntegerField(null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'get_latest_by': ['updated_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='historicalsentence',
            name='encoder_embedding',
            field=pgvector.django.vector.VectorField(dimensions=1024, null=True),
        ),
        migrations.AddField(
            model_name='sentence',
            name='encoder_embedding',
            field=pgvector.django.vector.VectorField(dimensions=1024, null=True),
        ),
        migrations.AddField(
            model_name='classifier',
            name='encoder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classifiers', to='scheduling.encoder'),
        ),
        migrations.AddField(
            model_name='historicalclassifier',
            name='encoder',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='scheduling.encoder'),
        ),
        migrations.AddField(
            model_name='historicalsentence',
            name='encoder',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='scheduling.encoder'),
        ),
        migrations.AddField(
            model_name='sentence',
            name='encoder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sentences', to='scheduling.encoder'),
        ),
        migrations.CreateModel(
            name='HistoricalEncoder',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('prod', 'Prod')], max_length=5)),
                ('base_model', models.CharField(max_length=100)),
                ('hf_repo_id', models.CharField(max_length=200)),
                ('hf_revision', models.CharField(max_length=100, null=True)),
                ('dimensions', models.PositiveSmallIntegerField()),
                ('accuracy_temporal', models.FloatField(null=True)),
                ('accuracy_confession', models.FloatField(null=True)),
                ('test_size', models.PositiveSmallIntegerField(null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical encoder',
                'verbose_name_plural': 'historical encoders',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
