# Generated by Django 5.2.14 on 2026-06-26 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0040_encoder_historicalsentence_encoder_embedding_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encoder',
            name='accuracy_confession',
        ),
        migrations.RemoveField(
            model_name='encoder',
            name='accuracy_temporal',
        ),
        migrations.RemoveField(
            model_name='encoder',
            name='test_size',
        ),
        migrations.RemoveField(
            model_name='historicalencoder',
            name='accuracy_confession',
        ),
        migrations.RemoveField(
            model_name='historicalencoder',
            name='accuracy_temporal',
        ),
        migrations.RemoveField(
            model_name='historicalencoder',
            name='test_size',
        ),
    ]
