# Generated by Django 5.2.14 on 2026-06-29 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0041_remove_encoder_accuracy_confession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsentencemoderation',
            name='category',
            field=models.CharField(choices=[('ml_mismatch', 'Ml Mismatch'), ('v2_outlier', 'V2 Outlier')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sentencemoderation',
            name='category',
            field=models.CharField(choices=[('ml_mismatch', 'Ml Mismatch'), ('v2_outlier', 'V2 Outlier')], max_length=20),
        ),
    ]
