# Generated by Django 5.2.15 on 2026-07-22 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0042_alter_historicalsentencemoderation_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpruning',
            name='ml_indices',
        ),
        migrations.RemoveField(
            model_name='pruning',
            name='ml_indices',
        ),
    ]
