# Generated by Django 5.2.15 on 2026-07-22 20:36

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0043_remove_historicalpruning_ml_indices_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsentence',
            name='action',
            field=models.CharField(blank=True, choices=[('start', 'START'), ('show', 'SHOW'), ('hide', 'HIDE'), ('stop', 'STOP')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalsentence',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
        migrations.AlterField(
            model_name='historicalsentence',
            name='encoder_embedding',
            field=pgvector.django.vector.VectorField(dimensions=1024),
        ),
        migrations.AlterField(
            model_name='historicalsentence',
            name='source',
            field=models.CharField(blank=True, choices=[('human', 'HUMAN'), ('ml', 'ML')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalsentence',
            name='transformer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='action',
            field=models.CharField(blank=True, choices=[('start', 'START'), ('show', 'SHOW'), ('hide', 'HIDE'), ('stop', 'STOP')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='classifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sentences', to='scheduling.classifier'),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='encoder_embedding',
            field=pgvector.django.vector.VectorField(dimensions=1024),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='source',
            field=models.CharField(blank=True, choices=[('human', 'HUMAN'), ('ml', 'ML')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='transformer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
