# Generated by Django 5.2.15 on 2026-07-22 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0044_alter_historicalsentence_action_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsentencemoderation',
            name='action',
        ),
        migrations.RemoveField(
            model_name='historicalsentencemoderation',
            name='other_action',
        ),
        migrations.RemoveField(
            model_name='sentencemoderation',
            name='action',
        ),
        migrations.RemoveField(
            model_name='sentencemoderation',
            name='other_action',
        ),
        migrations.AlterField(
            model_name='historicalsentencemoderation',
            name='category',
            field=models.CharField(choices=[('v2_outlier', 'V2 Outlier')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sentencemoderation',
            name='category',
            field=models.CharField(choices=[('v2_outlier', 'V2 Outlier')], max_length=20),
        ),
    ]
