# Generated by Django 5.2.15 on 2026-07-22 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0045_remove_historicalsentencemoderation_action_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsentence',
            name='action',
        ),
        migrations.RemoveField(
            model_name='historicalsentence',
            name='classifier',
        ),
        migrations.RemoveField(
            model_name='historicalsentence',
            name='embedding',
        ),
        migrations.RemoveField(
            model_name='historicalsentence',
            name='source',
        ),
        migrations.RemoveField(
            model_name='historicalsentence',
            name='transformer_name',
        ),
        migrations.RemoveField(
            model_name='sentence',
            name='action',
        ),
        migrations.RemoveField(
            model_name='sentence',
            name='classifier',
        ),
        migrations.RemoveField(
            model_name='sentence',
            name='embedding',
        ),
        migrations.RemoveField(
            model_name='sentence',
            name='source',
        ),
        migrations.RemoveField(
            model_name='sentence',
            name='transformer_name',
        ),
    ]
