# Generated by Django 5.2.15 on 2026-07-22 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0046_remove_historicalsentence_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classifier',
            name='target',
            field=models.CharField(choices=[('temporal', 'Temporal'), ('confession', 'Confession')], max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalclassifier',
            name='target',
            field=models.CharField(choices=[('temporal', 'Temporal'), ('confession', 'Confession')], max_length=10),
        ),
    ]
