# Generated by Django 5.2.15 on 2026-07-22 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0047_alter_classifier_target_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpruningmoderation',
            name='category',
            field=models.CharField(choices=[('v2_diff_human', 'V2 Diff Human')], max_length=16),
        ),
        migrations.AlterField(
            model_name='pruningmoderation',
            name='category',
            field=models.CharField(choices=[('v2_diff_human', 'V2 Diff Human')], max_length=16),
        ),
    ]
