# Generated by Django 5.2.14 on 2026-06-07 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0012_alter_churchmoderation_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='annuairecatholique_business_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='church',
            name='annuairecatholique_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='church',
            name='annuairecatholique_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalchurch',
            name='annuairecatholique_business_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalchurch',
            name='annuairecatholique_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalchurch',
            name='annuairecatholique_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='churchmoderation',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('messesinfo', 'Messesinfo'), ('lehavre', 'Lehavre'), ('trouverunemesse', 'Trouverunemesse'), ('annuairecatholique', 'Annuairecatholique')], max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalchurchmoderation',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('messesinfo', 'Messesinfo'), ('lehavre', 'Lehavre'), ('trouverunemesse', 'Trouverunemesse'), ('annuairecatholique', 'Annuairecatholique')], max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalparishmoderation',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('messesinfo', 'Messesinfo'), ('lehavre', 'Lehavre'), ('trouverunemesse', 'Trouverunemesse'), ('annuairecatholique', 'Annuairecatholique')], max_length=20),
        ),
        migrations.AlterField(
            model_name='parishmoderation',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('messesinfo', 'Messesinfo'), ('lehavre', 'Lehavre'), ('trouverunemesse', 'Trouverunemesse'), ('annuairecatholique', 'Annuairecatholique')], max_length=20),
        ),
    ]
