# Generated by Django 5.2.15 on 2026-07-15 16:43

from django.db import migrations, models


def backfill_historical_null_city_zipcode(apps, schema_editor):
    # Historical snapshots may carry NULL city/zipcode from before these fields were populated
    # (e.g. St-Pierre-la-Mer). They cannot go through Django admin, so fill them here with '' —
    # the honest value for a snapshot that genuinely had no city — before the columns become
    # NOT NULL. Live `church` rows are cleaned by hand beforehand; if any live NULL remains, the
    # AlterField below fails on purpose, signalling data that still needs a real value.
    HistoricalChurch = apps.get_model('registry', 'HistoricalChurch')
    HistoricalChurch.objects.filter(city__isnull=True).update(city='')
    HistoricalChurch.objects.filter(zipcode__isnull=True).update(zipcode='')


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0013_church_annuairecatholique_business_id_and_more'),
    ]

    operations = [
        migrations.RunPython(
            backfill_historical_null_city_zipcode,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='church',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='church',
            name='zipcode',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='historicalchurch',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalchurch',
            name='zipcode',
            field=models.CharField(max_length=5),
        ),
    ]
