# Generated by Django 5.2.15 on 2026-07-22 13:10

import core.models.db_functions
import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0015_immutable_unaccent'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('insee_code', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('zipcode', models.CharField(max_length=5)),
                ('population', models.PositiveIntegerField(default=0)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('name_norm', models.GeneratedField(db_persist=True, expression=django.db.models.functions.text.Replace(django.db.models.functions.text.Replace(django.db.models.functions.text.Lower(core.models.db_functions.ImmutableUnaccent('name')), models.Value('-'), models.Value(' ')), models.Value("'"), models.Value(' ')), output_field=models.TextField())),
            ],
            options={
                'indexes': [django.contrib.postgres.indexes.GistIndex(fields=['location'], name='registry_ci_locatio_720ca3_gist'), django.contrib.postgres.indexes.GinIndex(fields=['name_norm'], name='city_name_norm_trgm', opclasses=['gin_trgm_ops'])],
            },
        ),
    ]
