# Generated by Django 5.2.15 on 2026-07-24 21:42

import core.models.db_functions
import django.contrib.postgres.indexes
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0017_city_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parish',
            options={},
        ),
        migrations.AlterModelOptions(
            name='website',
            options={},
        ),
        migrations.AddField(
            model_name='church',
            name='name_norm',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.functions.text.Replace(django.db.models.functions.text.Replace(django.db.models.functions.text.Lower(core.models.db_functions.ImmutableUnaccent('name')), models.Value('-'), models.Value(' ')), models.Value("'"), models.Value(' ')), output_field=models.TextField()),
        ),
        migrations.AddField(
            model_name='parish',
            name='name_norm',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.functions.text.Replace(django.db.models.functions.text.Replace(django.db.models.functions.text.Lower(core.models.db_functions.ImmutableUnaccent('name')), models.Value('-'), models.Value(' ')), models.Value("'"), models.Value(' ')), output_field=models.TextField()),
        ),
        migrations.AddField(
            model_name='website',
            name='name_norm',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.functions.text.Replace(django.db.models.functions.text.Replace(django.db.models.functions.text.Lower(core.models.db_functions.ImmutableUnaccent('name')), models.Value('-'), models.Value(' ')), models.Value("'"), models.Value(' ')), output_field=models.TextField()),
        ),
        migrations.AddIndex(
            model_name='church',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name_norm'], name='church_name_norm_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='parish',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name_norm'], name='parish_name_norm_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='website',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name_norm'], name='website_name_norm_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
