# Generated by Django 5.2.15 on 2026-07-28 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0018_alter_parish_options_alter_website_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='nb_recent_hits',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalchurch',
            name='nb_recent_hits',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalparish',
            name='nb_recent_hits',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parish',
            name='nb_recent_hits',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
