# Generated by Django 5.2.15 on 2026-07-28 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0018_alter_parish_options_alter_website_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalwebsite',
            name='is_best_diocese_hit',
        ),
        migrations.RemoveField(
            model_name='historicalwebsite',
            name='nb_recent_hits',
        ),
        migrations.RemoveField(
            model_name='website',
            name='is_best_diocese_hit',
        ),
        migrations.RemoveField(
            model_name='website',
            name='nb_recent_hits',
        ),
    ]
