# Generated by Django 5.2.16 on 2026-10-05 11:17

import core.models.db_functions
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0020_immutable_unaccent_search_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalchurch',
            name='name_norm',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.functions.text.Replace(django.db.models.functions.text.Replace(django.db.models.functions.text.Lower(core.models.db_functions.ImmutableUnaccent('name')), models.Value('-'), models.Value(' ')), models.Value("'"), models.Value(' ')), output_field=models.TextField()),
        ),
        migrations.AddField(
            model_name='historicalparish',
            name='name_norm',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.functions.text.Replace(django.db.models.functions.text.Replace(django.db.models.functions.text.Lower(core.models.db_functions.ImmutableUnaccent('name')), models.Value('-'), models.Value(' ')), models.Value("'"), models.Value(' ')), output_field=models.TextField()),
        ),
        migrations.AddField(
            model_name='historicalwebsite',
            name='name_norm',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.functions.text.Replace(django.db.models.functions.text.Replace(django.db.models.functions.text.Lower(core.models.db_functions.ImmutableUnaccent('name')), models.Value('-'), models.Value(' ')), models.Value("'"), models.Value(' ')), output_field=models.TextField()),
        ),
    ]
