# Generated by Django 5.2.14 on 2026-06-30 13:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0011_autocompletehit'),
        ('registry', '0013_church_annuairecatholique_business_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CopilotDiscussion',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('running', 'Running'), ('awaiting_approval', 'Awaiting Approval'), ('error', 'Error')], default='idle', max_length=20)),
                ('pydantic_messages', models.JSONField(blank=True, default=list)),
                ('error_message', models.TextField(blank=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copilot_discussions', to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copilot_discussions', to='registry.website')),
            ],
            options={
                'get_latest_by': ['updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CopilotDiscussionItem',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveIntegerField()),
                ('item_type', models.CharField(choices=[('user_message', 'User Message'), ('agent_message', 'Agent Message'), ('autonomous_tool_call', 'Autonomous Tool Call'), ('proposed_tool_call', 'Proposed Tool Call')], max_length=30)),
                ('text', models.TextField(blank=True)),
                ('tool_name', models.CharField(blank=True, max_length=100)),
                ('tool_args', models.JSONField(blank=True, null=True)),
                ('tool_result', models.JSONField(blank=True, null=True)),
                ('tool_call_id', models.CharField(blank=True, max_length=100)),
                ('approval_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=10)),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='front.copilotdiscussion')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('discussion', 'position')},
            },
        ),
    ]
