# Generated by Django 5.2.14 on 2026-07-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0012_copilotdiscussion_copilotdiscussionitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copilotdiscussionitem',
            name='approval_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('failure', 'Failure')], max_length=10),
        ),
    ]
