# Generated by Django 5.2.15 on 2026-07-14 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0013_alter_copilotdiscussionitem_approval_status'),
        ('registry', '0013_church_annuairecatholique_business_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='registry.church'),
        ),
    ]
