# Generated by Django 5.2.15 on 2026-07-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0014_report_church'),
    ]

    operations = [
        migrations.AddField(
            model_name='copilotdiscussionitem',
            name='tool_args_before',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
