# Generated by Django 5.2.16 on 2026-08-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0016_conversation_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
