# Generated by Django 5.2.16 on 2026-09-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0018_historicalconversationmoderation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='complained_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
