# Generated by Django 5.2.17 on 2026-10-06 11:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0019_message_complained_at_message_delivered_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageImage',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('content', models.BinaryField()),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='front.message')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
