# Generated by Django 5.2.17 on 2026-10-09 13:19

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0022_approval_approvalcomment_historicalapproval'),
        ('registry', '0021_historicalchurch_name_norm_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalApprovalModeration',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('status', models.CharField(choices=[('to_validate', 'To Validate'), ('validated', 'Validated'), ('bug', 'Bug')], max_length=12)),
                ('comment', models.TextField(blank=True, default=None, null=True)),
                ('category', models.CharField(choices=[('new_approval', 'New Approval'), ('new_comment', 'New Comment')], max_length=16)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('approval', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='front.approval')),
                ('diocese', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registry.diocese')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical approval moderation',
                'verbose_name_plural': 'historical approval moderations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalIssueModeration',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('status', models.CharField(choices=[('to_validate', 'To Validate'), ('validated', 'Validated'), ('bug', 'Bug')], max_length=12)),
                ('comment', models.TextField(blank=True, default=None, null=True)),
                ('category', models.CharField(choices=[('new_issue', 'New Issue'), ('new_comment', 'New Comment')], max_length=16)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('diocese', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registry.diocese')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='front.issue')),
            ],
            options={
                'verbose_name': 'historical issue moderation',
                'verbose_name_plural': 'historical issue moderations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ApprovalModeration',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('to_validate', 'To Validate'), ('validated', 'Validated'), ('bug', 'Bug')], max_length=12)),
                ('comment', models.TextField(blank=True, default=None, null=True)),
                ('category', models.CharField(choices=[('new_approval', 'New Approval'), ('new_comment', 'New Comment')], max_length=16)),
                ('approval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderations', to='front.approval')),
                ('diocese', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_moderations', to='registry.diocese')),
            ],
            options={
                'unique_together': {('approval', 'category')},
            },
        ),
        migrations.CreateModel(
            name='IssueModeration',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('to_validate', 'To Validate'), ('validated', 'Validated'), ('bug', 'Bug')], max_length=12)),
                ('comment', models.TextField(blank=True, default=None, null=True)),
                ('category', models.CharField(choices=[('new_issue', 'New Issue'), ('new_comment', 'New Comment')], max_length=16)),
                ('diocese', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_moderations', to='registry.diocese')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderations', to='front.issue')),
            ],
            options={
                'unique_together': {('issue', 'category')},
            },
        ),
    ]
