# Generated by Django 5.2.17 on 2026-10-09 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0023_historicalapprovalmoderation_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReportModeration',
        ),
        migrations.DeleteModel(
            name='HistoricalReportModeration',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
