# Generated by Django 5.2.14 on 2026-07-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0014_alter_crawlingmoderation_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalscraping',
            name='url',
            field=models.URLField(max_length=512),
        ),
        migrations.AlterField(
            model_name='scraping',
            name='url',
            field=models.URLField(max_length=512),
        ),
        migrations.AlterField(
            model_name='websiteforbiddenpath',
            name='path',
            field=models.CharField(max_length=512),
        ),
    ]
