server {
    listen 80;
    listen [::]:80;

    server_name {{ front_server_host }};

    access_log /var/log/nginx/{{ front_app_name }}-http-access.log;
    error_log /var/log/nginx/{{ front_app_name }}-http-error.log info;

    location /.well-known/acme-challenge {
        root /var/www/letsencrypt;
        try_files $uri $uri/ =404;
    }

    location / {
        rewrite ^ https://{{ front_server_host }}$request_uri? permanent;
    }
}
