#!/bin/bash

### Start the Next.js front as a node {{ node_major }} process (bound to localhost, behind nginx)

cd {{ front_app_dir }}

# Load the templated env (NEXT_PUBLIC_MAP_TILER_API_KEY, CRON_SECRET) into the process environment
set -a
. {{ front_app_dir }}/.env.local
set +a

export NODE_ENV=production

exec /usr/bin/node node_modules/next/dist/bin/next start -p {{ front_port }} -H 127.0.0.1
