# Generated by Django 5.2.14 on 2026-06-06 14:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attaching', '0004_alter_historicalimage_website_alter_image_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='PdfRecognition',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pdf_name', models.CharField(max_length=256)),
                ('pdf_sha256', models.CharField(max_length=64, unique=True)),
                ('llm_html', models.TextField(blank=True, null=True)),
                ('llm_provider', models.CharField(blank=True, choices=[('openai', 'OPENAI')], null=True)),
                ('llm_model', models.CharField(blank=True, max_length=100, null=True)),
                ('prompt_hash', models.CharField(blank=True, max_length=32, null=True)),
                ('llm_error_detail', models.TextField(blank=True, null=True)),
            ],
            options={
                'get_latest_by': ['updated_at'],
                'abstract': False,
            },
        ),
    ]
