# Generated by Django 5.2.14 on 2026-06-06 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attaching', '0005_pdfrecognition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdfrecognition',
            name='pdf_name',
        ),
        migrations.AddField(
            model_name='pdfrecognition',
            name='pdf_url',
            field=models.URLField(default=None, max_length=300),
            preserve_default=False,
        ),
    ]
