# Generated by Django 5.2.14 on 2026-06-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attaching', '0006_remove_pdfrecognition_pdf_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfrecognition',
            name='nb_pages',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pdfrecognition',
            name='pdf_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
