# Generated by Django 5.2.17 on 2026-10-09 12:29

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attaching', '0008_historicalimagemoderation_imagemoderation'),
        ('registry', '0021_historicalchurch_name_norm_and_more'),
        ('scheduling', '0048_alter_historicalpruningmoderation_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileNote',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('ip_address_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('active', 'Active'), ('censored', 'Censored')], default='open', max_length=8)),
                ('expire_at', models.DateTimeField()),
                ('name', models.CharField(max_length=256)),
                ('caption', models.TextField(blank=True, null=True)),
                ('mime_type', models.CharField(max_length=100)),
                ('llm_html', models.TextField(blank=True, null=True)),
                ('llm_provider', models.CharField(blank=True, choices=[('openai', 'OPENAI')], null=True)),
                ('llm_model', models.CharField(blank=True, max_length=100, null=True)),
                ('llm_prompt_hash', models.CharField(blank=True, max_length=32, null=True)),
                ('llm_error_detail', models.TextField(blank=True, null=True)),
                ('human_html', models.TextField(blank=True, null=True)),
                ('church', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_notes', to='registry.church')),
                ('prunings', models.ManyToManyField(related_name='file_notes', to='scheduling.pruning')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_notes', to='registry.website')),
            ],
            options={
                'get_latest_by': ['updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FileNoteComment',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('ip_address_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('content', models.TextField()),
                ('file_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='attaching.filenote')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': ['updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalFileNote',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('ip_address_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('active', 'Active'), ('censored', 'Censored')], default='open', max_length=8)),
                ('expire_at', models.DateTimeField()),
                ('name', models.CharField(max_length=256)),
                ('caption', models.TextField(blank=True, null=True)),
                ('mime_type', models.CharField(max_length=100)),
                ('llm_html', models.TextField(blank=True, null=True)),
                ('llm_provider', models.CharField(blank=True, choices=[('openai', 'OPENAI')], null=True)),
                ('llm_model', models.CharField(blank=True, max_length=100, null=True)),
                ('llm_prompt_hash', models.CharField(blank=True, max_length=32, null=True)),
                ('llm_error_detail', models.TextField(blank=True, null=True)),
                ('human_html', models.TextField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('church', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registry.church')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registry.website')),
            ],
            options={
                'verbose_name': 'historical file note',
                'verbose_name_plural': 'historical file notes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalTextNote',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('ip_address_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('active', 'Active'), ('censored', 'Censored')], default='open', max_length=8)),
                ('expire_at', models.DateTimeField()),
                ('content', models.TextField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('church', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registry.church')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='registry.website')),
            ],
            options={
                'verbose_name': 'historical text note',
                'verbose_name_plural': 'historical text notes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='TextNote',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('ip_address_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('active', 'Active'), ('censored', 'Censored')], default='open', max_length=8)),
                ('expire_at', models.DateTimeField()),
                ('content', models.TextField()),
                ('church', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='text_notes', to='registry.church')),
                ('prunings', models.ManyToManyField(related_name='text_notes', to='scheduling.pruning')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_notes', to='registry.website')),
            ],
            options={
                'get_latest_by': ['updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TextNoteComment',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('ip_address_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('content', models.TextField()),
                ('text_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='attaching.textnote')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': ['updated_at'],
                'abstract': False,
            },
        ),
    ]
